In [4]:
# [예제 3.1] 아파트 매매, 전세 지수 데이터 전처리 시키기
import xlwings as xw
import pandas as pd

def KBpriceindex_preprocessing(path, data_type):
    # path : KB 데이터 엑셀 파일의 디렉토리 (문자열)
    # data_type : ‘매매종합’, ‘매매APT’, ‘매매연립’, ‘매매단독’, ‘전세종합’, ‘전세APT’, ‘전세연립’, ‘전세단독’ 중 하나
    
    wb = xw.Book(path)                
    sheet = wb.sheets[data_type]   
    row_num = sheet.range((1,1)).end('down').end('down').end('down').row  
    data_range = 'A2:GE' + str(row_num)
    raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value 
    
    bignames = '서울 대구 부산 대전 광주 인천 울산 세종 경기 강원 충북 충남 전북 전남 경북 경남 제주도 6개광역시 5개광역시 수도권 기타지방 구분 전국'
    bigname_list = bignames.split(' ')
    big_col = list(raw_data.columns)
    small_col = list(raw_data.iloc[0])

    for num, gu_data in enumerate(small_col):
        if gu_data == None:
            small_col[num] = big_col[num]

        check = num
        while True:
            if big_col[check] in bigname_list:
                big_col[num] = big_col[check]
                break
            else:
                check = check - 1
                
    big_col[129] = '경기' 
    big_col[130] = '경기'
    small_col[185] = '서귀포'
    
    raw_data.columns = [big_col, small_col]
    new_col_data = raw_data.drop([0,1])
    
    index_list = list(new_col_data['구분']['구분'])

    new_index = []

    for num, raw_index in enumerate(index_list):
        temp = str(raw_index).split('.')
        if int(temp[0]) > 12 :
            if len(temp[0]) == 2:
                new_index.append('19' + temp[0] + '.' + temp[1])
            else:
                new_index.append(temp[0] + '.' + temp[1])
        else:
            new_index.append(new_index[num-1].split('.')[0] + '.' + temp[0])

    new_col_data.set_index(pd.to_datetime(new_index), inplace=True)
    cleaned_data  = new_col_data.drop(('구분', '구분'), axis=1)
    return cleaned_data


path = r'data/★(월간)KB주택가격동향_시계열(2019.01)12831994601335062.xls'
price_index = KBpriceindex_preprocessing(path, '매매apt')
jeonse_index = KBpriceindex_preprocessing(path, '전세apt')
price_index
jeonse_index

                 전국       서울                                               \
                 전국       서울       강북      강북구      광진구      노원구      도봉구
1986-01-01  10.7932  9.78174  10.7305     None     None     None     None
1986-02-01  11.1043  10.1955  10.8564     None     None     None     None
1986-03-01  11.4464  10.5501  11.1396     None     None     None     None
1986-04-01  11.6952  10.7865  11.3284     None     None     None     None
1986-05-01  11.7263  10.8752  11.5172     None     None     None     None
1986-06-01  11.6641  10.7865  11.5172     None     None     None     None
1986-07-01   11.633  10.7865  11.6116     None     None     None     None
1986-08-01  11.7263  10.8752  11.6116     None     None     None     None
1986-09-01  12.0374  11.3184  11.7375     None     None     None     None
1986-10-01  12.1307   11.348  11.8948     None     None     None     None
1986-11-01  11.8508  10.8752  11.8004     None     None     None     None
1986-12-01  11.6019  10.5205   11.706     None     None     None     None
1987-01-01   11.633  10.6979  11.6116     None     None     None     None
1987-02-01  11.9441   11.082  11.6745     None     None     None     None
1987-03-01  12.3484  11.4958  12.1151     None     None     None     None
1987-04-01  12.7217  11.8504  12.3668     None     None     None     None
1987-05-01  12.8461  11.9095  12.3983     None     None     None     None
1987-06-01  12.9083  11.9981  12.5871     None     None     None     None
1987-07-01  12.9705  11.9981  12.5871     None     None     None     None
1987-08-01  13.0638  12.0868  12.7444     None     None     None     None
1987-09-01  13.7792  12.6778  13.0591     None     None     None     None
1987-10-01  13.9659   12.796  13.5941     None     None     None     None
1987-11-01  14.2769   13.062  13.9402     None     None     None     None
1987-12-01  14.2769   13.062  13.9402     None     None     None     None
1988-01-01  14.4946  13.2984  13.9402     None     None     None     None
1988-02-01  15.0234  13.8599  14.3808     None     None     None     None
1988-03-01  15.6455  14.4805  15.0101     None     None     None     None
1988-04-01   16.081  14.8056   15.136     None     None     None     None
1988-05-01  16.3298  14.8647  15.7024     None     None     None     None
1988-06-01  16.3609  14.6874  15.3248     None     None     None     None
...             ...      ...      ...      ...      ...      ...      ...
2016-08-01  99.7284  95.6314  95.4878  94.5874  94.4084  97.3163  96.5653
2016-09-01  99.8233  95.8095  95.8069  94.9645  94.5415  97.5853   96.904
2016-10-01  100.025   96.112  96.2438  95.5614   94.997  97.9447  97.0783
2016-11-01  100.263  96.3735  96.5788  95.9362  95.2604  98.2108  97.5019
2016-12-01  100.345  96.4995  96.7262  96.1059    95.34  98.3911  97.6155
2017-01-01  100.381  96.5566  96.8015  96.2734  95.3933  98.5074  97.6937
2017-02-01  100.404  96.5834  96.8341  96.4531  95.3336  98.5354  97.6938
2017-03-01  100.415  96.6243  96.8994  96.4585  95.3336  98.6417  97.7054
2017-04-01   100.43  96.6971  96.9758  96.4818  95.3319  98.7428  97.7211
2017-05-01  100.456  96.8044  97.0524  96.5048  95.3467  98.8507  97.8014
2017-06-01  100.521  97.1108  97.3002  96.5708  96.0179  99.1336  98.0909
2017-07-01  100.584  97.4544  97.6228  96.6811  96.3286  99.6093    98.51
2017-08-01  100.636  97.7994  97.8932  97.0458  96.7319  99.9381  98.7816
2017-09-01  100.644  97.9557  98.0493  97.1899  97.0868  100.033  98.7983
2017-10-01   100.67  98.1373  98.1799  97.4362  97.3825  99.9966   99.051
2017-11-01  100.654   98.338  98.3535  97.6107  98.1109  99.9633  99.0558
2017-12-01  100.631   98.507  98.4142  97.6526  98.4636  99.7444  99.0735
2018-01-01  100.607  98.6868    98.53  97.7546  98.9907  99.6424  99.1461
2018-02-01  100.582  98.8057  98.6244  97.8864  99.3394  99.6178  99.1461
2018-03-01  100.541  98.9218  98.8006  98.0804  99.4446  99.6349  99.1461
2018-04-01  100.462  98.9139  98.8495  98.2067  99.2704  99.5394  99.1196
2018-05-01  100.346  98.8449  98.8791  98.3145  99.2117  99.5066  99.1169
2018-06-01   100.24   98.809  98.8949  98.4889  99.1624  99.4924  99.0599
2018-07-01  100.102  98.8427    98.94  98.5473  98.9196  99.4903  99.0599
2018-08-01  100.057  99.0158  99.1105  98.6382  98.8128   99.562   99.339
2018-09-01  100.126  99.6026  99.6567  99.3046  99.3778  99.7619  99.5864
2018-10-01  100.184  100.078  99.9773  99.7664  99.7543  99.9306  99.9811
2018-11-01  100.166  100.197  100.096  100.012   99.951  100.044  100.055
2018-12-01  100.066  100.101  100.063  100.012      100  100.035  100.102
2019-01-01      100      100      100      100      100      100      100

                                       ...       경남                    \
               동대문구      마포구     서대문구  ...      의창구      진해구       양산
1986-01-01     None     None     None  ...     None     None     None
1986-02-01     None     None     None  ...     None     None     None
1986-03-01     None     None     None  ...     None     None     None
1986-04-01     None     None     None  ...     None     None     None
1986-05-01     None     None     None  ...     None     None     None
1986-06-01     None     None     None  ...     None     None     None
1986-07-01     None     None     None  ...     None     None     None
1986-08-01     None     None     None  ...     None     None     None
1986-09-01     None     None     None  ...     None     None     None
1986-10-01     None     None     None  ...     None     None     None
1986-11-01     None     None     None  ...     None     None     None
1986-12-01     None     None     None  ...     None     None     None
1987-01-01     None     None     None  ...     None     None     None
1987-02-01     None     None     None  ...     None     None     None
1987-03-01     None     None     None  ...     None     None     None
1987-04-01     None     None     None  ...     None     None     None
1987-05-01     None     None     None  ...     None     None     None
1987-06-01     None     None     None  ...     None     None     None
1987-07-01     None     None     None  ...     None     None     None
1987-08-01     None     None     None  ...     None     None     None
1987-09-01     None     None     None  ...     None     None     None
1987-10-01     None     None     None  ...     None     None     None
1987-11-01     None     None     None  ...     None     None     None
1987-12-01     None     None     None  ...     None     None     None
1988-01-01     None     None     None  ...     None     None     None
1988-02-01     None     None     None  ...     None     None     None
1988-03-01     None     None     None  ...     None     None     None
1988-04-01     None     None     None  ...     None     None     None
1988-05-01     None     None     None  ...     None     None     None
1988-06-01     None     None     None  ...     None     None     None
...             ...      ...      ...  ...      ...      ...      ...
2016-08-01  95.1123  93.6359  94.3881  ...   109.39  109.934  102.215
2016-09-01  95.5743  94.0105  94.8148  ...  109.231  109.929  102.165
2016-10-01  95.8738  94.6815    95.58  ...  109.231  109.929   102.33
2016-11-01  96.3444  95.0538  95.7906  ...  109.231  109.929  102.851
2016-12-01  96.4542  95.2407  96.1228  ...  109.293  110.084  102.682
2017-01-01  96.4947  95.3901  96.2205  ...  109.193  110.086  102.453
2017-02-01  96.5841  95.5605  96.3265  ...  109.192  109.818   102.18
2017-03-01  96.5998  95.6199  96.5269  ...  108.833  109.464  101.924
2017-04-01  96.6067  95.7894  96.5987  ...  108.744  109.047  101.811
2017-05-01  96.6466  95.9703  96.6896  ...  108.609  108.643   101.54
2017-06-01  96.6925  96.0464  96.8677  ...  108.156   108.06  101.161
2017-07-01  96.9269  96.4087  97.1726  ...  107.771  107.643   101.08
2017-08-01  97.4815  96.7528  97.3105  ...  107.104  107.605   100.64
2017-09-01   97.721  96.9269  97.4872  ...  106.259  106.619  100.507
2017-10-01   97.721  97.0346  97.6212  ...  105.291  105.943  100.501
2017-11-01  98.0465  97.1905  97.9305  ...  104.023   105.38  100.215
2017-12-01  98.2082  97.3499  98.0712  ...  103.506  104.906  100.182
2018-01-01  98.3082  97.5298  98.2225  ...  102.926  104.354  100.131
2018-02-01  98.5099  97.7887  98.2412  ...  102.805  104.272  100.131
2018-03-01  98.9082   98.099  98.5745  ...   102.61   103.99  99.8943
2018-04-01  99.0555  98.1587  98.7959  ...  101.996  103.409  99.6455
2018-05-01  99.1281  98.2565  98.7547  ...  101.621  102.757   99.581
2018-06-01  99.1037  98.4122  98.8363  ...  101.532  101.644  99.3073
2018-07-01  98.9525  98.5215  98.8992  ...   101.28  101.267  99.3073
2018-08-01   98.936  99.1981  99.0987  ...  101.006   100.71    99.16
2018-09-01  99.4387  100.146  99.8637  ...  100.441   100.21  99.2478
2018-10-01  99.6623   100.31  100.395  ...  100.422  100.392  99.6344
2018-11-01  99.9493  100.206  100.473  ...  100.255  100.242  99.9103
2018-12-01      100  100.126  100.179  ...  100.186      100      100
2019-01-01      100      100      100  ...      100      100      100

                                                 제주도              기타지방
                 거제       진주       김해       통영   제주도      서귀포     기타지방
1986-01-01     None     None     None     None  None     None     None
1986-02-01     None     None     None     None  None     None     None
1986-03-01     None     None     None     None  None     None     None
1986-04-01     None     None     None     None  None     None     None
1986-05-01     None     None     None     None  None     None     None
1986-06-01     None     None     None     None  None     None     None
1986-07-01     None     None     None     None  None     None     None
1986-08-01     None     None     None     None  None     None     None
1986-09-01     None     None     None     None  None     None     None
1986-10-01     None     None     None     None  None     None     None
1986-11-01     None     None     None     None  None     None     None
1986-12-01     None     None     None     None  None     None     None
1987-01-01     None     None     None     None  None     None     None
1987-02-01     None     None     None     None  None     None     None
1987-03-01     None     None     None     None  None     None     None
1987-04-01     None     None     None     None  None     None     None
1987-05-01     None     None     None     None  None     None     None
1987-06-01     None     None     None     None  None     None     None
1987-07-01     None     None     None     None  None     None     None
1987-08-01     None     None     None     None  None     None     None
1987-09-01     None     None     None     None  None     None     None
1987-10-01     None     None     None     None  None     None     None
1987-11-01     None     None     None     None  None     None     None
1987-12-01     None     None     None     None  None     None     None
1988-01-01     None     None     None     None  None     None     None
1988-02-01     None     None     None     None  None     None     None
1988-03-01     None     None     None     None  None     None     None
1988-04-01     None     None     None     None  None     None     None
1988-05-01     None     None     None     None  None     None     None
1988-06-01     None     None     None     None  None     None     None
...             ...      ...      ...      ...   ...      ...      ...
2016-08-01  120.322  101.085  108.808  108.292  None  98.6522  103.434
2016-09-01  120.047  101.304  108.829  108.266  None  99.1227  103.438
2016-10-01  119.558  101.551  109.313  108.084  None  99.3697   103.47
2016-11-01  119.042  101.804  109.528  108.052  None  99.9394  103.535
2016-12-01   118.81  101.956  109.628  108.002  None  100.212  103.518
2017-01-01  117.485  102.206   109.39  107.797  None  100.502  103.442
2017-02-01  117.351  102.422  109.235  107.797  None  100.661  103.387
2017-03-01  116.985  102.791  109.168  107.473  None  100.744  103.331
2017-04-01  116.719  102.996  108.965  107.402  None   100.78  103.261
2017-05-01  116.622  103.074  108.875  107.347  None  100.776  103.194
2017-06-01  114.875  103.328  108.577  107.347  None  100.724  103.042
2017-07-01  113.311  103.328  108.408  107.347  None  100.593  102.926
2017-08-01  112.571  103.328  107.686  106.589  None  100.436  102.749
2017-09-01  112.455  103.407  107.256  105.947  None  100.428  102.599
2017-10-01  112.373  103.447  106.886  105.947  None  100.427  102.507
2017-11-01  111.767  103.631  106.693  105.884  None  100.321  102.357
2017-12-01   111.46  103.631  106.614  105.792  None  100.321  102.284
2018-01-01  110.863  103.635   106.54  105.739  None  100.279   102.19
2018-02-01  110.863  103.635  106.117  105.572  None  100.279   102.11
2018-03-01   110.41   103.62  105.917  105.416  None  100.241   101.98
2018-04-01  108.838  103.559  105.452   104.94  None  100.167  101.786
2018-05-01   106.62  103.559  104.854   104.57  None  100.155   101.61
2018-06-01  104.857  103.525  104.537  103.988  None  100.173  101.413
2018-07-01   103.17  103.405   103.76  103.988  None  100.024  101.144
2018-08-01   103.17  103.322  103.131  103.763  None  100.008  100.949
2018-09-01  101.979  102.867  102.492  101.672  None  100.038  100.722
2018-10-01  100.678  102.298  101.726  100.602  None  100.062  100.522
2018-11-01   100.54  101.305   100.86  100.118  None  100.077  100.253
2018-12-01      100  100.409  100.452      100  None  100.059  100.072
2019-01-01      100      100      100      100  None      100      100

[397 rows x 186 columns]

In [5]:
# [예제 3.2] KBpriceindex_preprocessing 함수 실행

import xlwings as xw

def KBpriceindex_preprocessing(path, data_type):
    # path : KB 데이터 엑셀 파일의 디렉토리 (문자열)
    # data_type : ‘매매종합’, ‘매매APT’, ‘매매연립’, ‘매매단독’, ‘전세종합’, ‘전세APT’, ‘전세연립’, ‘전세단독’ 중 하나
    
    wb = xw.Book(path)                
    sheet = wb.sheets[data_type]   
    row_num = sheet.range((1,1)).end('down').end('down').end('down').row  
    data_range = 'A2:GE' + str(row_num)
    raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value 
    
    bignames = '서울 대구 부산 대전 광주 인천 울산 세종 경기 강원 충북 충남 전북 전남 경북 경남 제주도 6개광역시 5개광역시 수도권 기타지방 구분 전국'
    bigname_list = bignames.split(' ')
    big_col = list(raw_data.columns)
    small_col = list(raw_data.iloc[0])

    for num, gu_data in enumerate(small_col):
        if gu_data == None:
            small_col[num] = big_col[num]

        check = num
        while True:
            if big_col[check] in bigname_list:
                big_col[num] = big_col[check]
                break
            else:
                check = check - 1
                
    big_col[129] = '경기' 
    big_col[130] = '경기'
    small_col[185] = '서귀포'
    
    raw_data.columns = [big_col, small_col]
    new_col_data = raw_data.drop([0,1])
    
    index_list = list(new_col_data['구분']['구분'])

    new_index = []

    for num, raw_index in enumerate(index_list):
        temp = str(raw_index).split('.')
        if int(temp[0]) > 20 :
            if len(temp[0]) == 2:
                new_index.append('19' + temp[0] + '.' + temp[1])
            else:
                new_index.append(temp[0] + '.' + temp[1])
        else:
            new_index.append(new_index[num-1].split('.')[0] + '.' + temp[0])

    new_col_data.set_index(pd.to_datetime(new_index), inplace=True)
    cleaned_data  = new_col_data.drop(('구분', '구분'), axis=1)
    return cleaned_data

In [6]:
# [예제 3.3] 아파트 매매가 지수, 전세가 지수 가져오기

import pandas as pd

path = r'data/★(월간)KB주택가격동향_시계열(2019.01)12831994601335062.xls'
price_index = KBpriceindex_preprocessing(path, '매매apt')
jeonse_index = KBpriceindex_preprocessing(path, '전세apt')

In [17]:
# [예제 3.4] 매매가 지수 데이터프레임에서 날짜를 기준으로 데이터 가져오기

from datetime import datetime
from dateutil.relativedelta import relativedelta

index_date = datetime(2019, 1, 1)
time_range = 12 * 15
prev_date = index_date - relativedelta(months=time_range)

print(index_date)
print(prev_date)

price_index.loc[index_date]
price_rate = price_index.loc[index_date] - price_index.loc[prev_date]
price_rate
# jeonse_rate = jeonse_index.loc[index_date] - jeonse_index.loc[prev_date]
# price_rate - jeonse_rate

2019-01-01 00:00:00
2004-01-01 00:00:00

전국     전국       38.7599
서울     서울       44.0898
       강북       42.3659
       강북구      36.0623
       광진구      40.0728
       노원구      46.7412
       도봉구      36.8764
       동대문구     38.6686
       마포구      45.3385
       서대문구     36.7315
       성동구      48.2977
       성북구      38.2218
       용산구      47.8355
       은평구      34.2402
       종로구      33.9431
       중구       34.1291
       중랑구      35.9912
       강남       45.0264
       강남구      45.2398
       강동구      42.8414
       강서구      41.5011
       관악구      40.6615
       구로구      42.0323
       금천구      39.5979
       동작구      45.8475
       서초구      49.6836
       송파구      43.3018
       양천구      44.1023
       영등포구     50.1007
6개광역시  6개광역시    39.8077
                 ...
전북     익산       43.2549
       군산        37.803
전남     전남       29.5134
       목포       33.3255
       순천       27.6784
       광양       17.0035
       여수           NaN
경북     경북       34.3152
       포항       28.2775
       남구       26.4854
       북구       29.6834
       구미       31.7193
       경산       44.9335
       안동           NaN
       김천           NaN
경남     경남        36.013
       창원       42.6565
       마산합포구        NaN
       마산회원구        NaN
       성산구          NaN
       의창구          NaN
       진해구          NaN
       양산       34.9492
       거제       29.6234
       진주       25.7987
       김해       39.2382
       통영           NaN
제주도    제주도          NaN
       서귀포      41.8172
기타지방   기타지방     36.1616
Length: 186, dtype: object

In [18]:
# [예제 3.5] 1년 동안의 매매가 지수 증감 구하기

(price_index.loc[index_date] - price_index.loc[prev_date])/price_index.loc[prev_date]

전국     전국       0.632916
서울     서울       0.788581
       강북       0.735085
       강북구      0.564021
       광진구      0.668691
       노원구      0.877625
       도봉구      0.584194
       동대문구     0.630487
       마포구      0.829441
       서대문구     0.580566
       성동구      0.934151
       성북구      0.618694
       용산구      0.917013
       은평구      0.520686
       종로구      0.513846
       중구       0.518122
       중랑구      0.562286
       강남       0.819054
       강남구      0.826143
       강동구      0.749517
       강서구      0.709434
       관악구      0.685247
       구로구      0.725099
       금천구      0.655571
       동작구      0.846636
       서초구      0.987423
       송파구      0.763726
       양천구      0.788982
       영등포구      1.00404
6개광역시  6개광역시    0.661341
                  ...
전북     익산       0.762268
       군산       0.607794
전남     전남        0.41871
       목포       0.499823
       순천       0.382714
       광양        0.20487
       여수            NaN
경북     경북       0.522423
       포항       0.394263
       남구       0.360274
       북구       0.422139
       구미       0.464543
       경산       0.815985
       안동            NaN
       김천            NaN
경남     경남       0.562818
       창원       0.743877
       마산합포구         NaN
       마산회원구         NaN
       성산구           NaN
       의창구           NaN
       진해구           NaN
       양산        0.53726
       거제       0.420927
       진주       0.347686
       김해       0.645771
       통영            NaN
제주도    제주도           NaN
       서귀포      0.718721
기타지방   기타지방     0.566456
Length: 186, dtype: object

In [39]:
# [예제 3.6] 매매가, 전세가 지수 증감률을 계산해서 데이터프레임 형태로 저장(ch03/ 3.1 부동산 수요.ipynb)

demand_df = pd.DataFrame()
demand_df['매매증감률'] = (price_index.loc[index_date] - price_index.loc[prev_date])/ price_index.loc[prev_date]
demand_df['전세증감률'] = (jeonse_index.loc[index_date] - jeonse_index.loc[prev_date])/jeonse_index.loc[prev_date]
demand_df['전세증감률']
price_ratio = demand_df['매매증감률'] - demand_df['매매증감률'][('전국','전국')]
jeonse_ratio = demand_df['전세증감률'] - demand_df['전세증감률'][('전국','전국')]
bubble = price_ratio - jeonse_ratio
pd.set_option('display.max_rows', 1000)
bubble = bubble * 100
bubble = bubble.sort_values()
bubble['rank'] = bubble.rank()
bubble

# demand_df['매매증감률'] - demand_df['전세증감률']

경기     용인                                                -70.2497
       남양주                                                -67.845
       화성                                                -38.0359
       분당구                                               -37.8398
       단원구                                               -34.2648
       양주                                                -34.2084
       일산서구                                              -33.3083
       김포                                                -31.5281
       구리                                                -31.3023
       고양                                                -31.1811
       일산동구                                              -29.6758
       성남                                                -29.4794
서울     강북구                                               -29.2936
경기     장안구                                               -29.2026
       덕양구                                               -28.9019
       의정부                                               -28.4799
       경기                                                -27.7795
       안산                                                -27.5202
       수원                                                -25.4622
서울     강서구                                               -24.7356
대전     유성구                                               -23.7631
경기     광주                                                -23.3469
       오산                                                 -21.923
       하남                                                -20.7201
충남     아산                                                -20.6946
경기     부천                                                -20.5591
서울     양천구                                               -20.2377
경기     권선구                                               -19.8525
서울     성북구                                               -19.8116
경기     상록구                                               -19.2172
       동안구                                               -18.1591
       파주                                                -18.0721
서울     중랑구                                               -18.0426
       구로구                                               -17.9425
충남     논산                                                 -17.885
인천     부평구                                               -17.4383
경기     안양                                                -16.3207
인천     연수구                                               -16.0319
서울     마포구                                               -15.8089
수도권    수도권                                               -15.3131
서울     관악구                                               -15.0793
충남     충남                                                -14.8208
서울     광진구                                               -14.3904
경기     군포                                                -14.1634
       만안구                                               -13.9134
       의왕                                                -13.8265
충북     충주                                                -13.7439
경기     시흥                                                -13.3878
대전     서구                                                -13.3292
충남     천안                                                -12.5913
서울     금천구                                               -11.1949
       동작구                                               -10.4557
       도봉구                                               -10.0576
경기     이천                                                -7.71445
인천     서구                                                -7.13544
       인천                                                -6.39206
경기     평택                                                 -6.1514
       팔달구                                               -6.02761
       동두천                                               -5.80882
       중원구                                               -5.28921
서울     중구                                                -4.92968
       종로구                                               -4.29827
       은평구                                               -4.17209
대전     대전                                                -3.94964
서울     강북                                                -3.79666
경남     거제                                                -1.97195
서울     영등포구                                              -1.76933
       서울                                               -0.554183
       서대문구                                             -0.292644
인천     남동구                                              -0.245679
전국     전국                                                       0
충북     충북                                                0.430411
인천     계양구                                               0.702614
전북     군산                                                0.931105
서울     강남                                                0.955568
       성동구                                                1.01317
부산     북구                                                 1.41153
대구     북구                                                   1.942
전남     순천                                                  2.6923
서울     동대문구                                               2.76489
인천     중구                                                 4.34864
강원     춘천                                                 4.41689
대전     동구                                                 5.88035
인천     미추홀구                                               5.94872
전남     전남                                                 5.98704
대구     달성군                                                6.38107
경기     수정구                                                6.67302
서울     노원구                                                6.89102
대구     달서구                                                7.78612
기타지방   기타지방                                               7.82994
충북     상당구                                                8.87763
경북     북구                                                 8.96945
충북     청주                                                 9.01619
서울     서초구                                                9.06537
경남     양산                                                 9.45034
충북     흥덕구                                                9.65607
울산     울주군                                                9.76015
경기     광명                                                 10.2156
서울     송파구                                                10.2383
부산     해운대구                                               10.6354
울산     북구                                                 10.9919
경북     포항                                                 11.1802
경남     경남                                                 12.0834
강원     강원                                                 12.1122
경남     김해                                                 12.6135
6개광역시  6개광역시                                              12.8573
대구     대구                                                  12.883
경남     진주                                                 12.9301
전북     전북                                                 13.0462
       완산구                                                13.3236
인천     동구                                                 13.6458
경북     구미                                                 13.7168
전북     전주                                                 13.7301
       덕진구                                                13.7589
서울     강동구                                                13.7611
대구     수성구                                                14.0296
전남     목포                                                 14.0738
강원     강릉                                                 14.2034
대구     서구                                                 14.5211
경북     경북                                                 14.5266
대전     대덕구                                                15.0181
경기     안성                                                 15.1904
경북     남구                                                 15.2399
전남     광양                                                 17.1928
5개광역시  5개광역시                                              17.3487
강원     원주                                                 17.5964
부산     연제구                                                18.3744
       서구                                                 18.3966
충남     공주                                                 18.5832
전북     익산                                                 20.1218
광주     북구                                                 20.2713
대전     중구                                                 20.7547
서울     강남구                                                21.2072
부산     부산                                                 23.0769
경북     경산                                                 23.7419
광주     동구                                                 23.8619
       남구                                                 24.3754
제주도    서귀포                                                24.7496
부산     남구                                                 25.1307
광주     광주                                                 25.3337
경기     과천                                                 25.8163
울산     울산                                                 26.6085
부산     중구                                                 27.0235
       영도구                                                27.3455
       사상구                                                 27.612
       동구                                                  28.306
광주     서구                                                  28.865
부산     기장군                                                29.2447
광주     광산구                                                29.4224
부산     부산진구                                               29.4762
       사하구                                                29.8309
서울     용산구                                                30.5604
부산     동래구                                                30.7229
울산     중구                                                 32.0267
부산     금정구                                                32.9233
울산     남구                                                 34.7041
대구     남구                                                 37.5042
       동구                                                 37.7288
울산     동구                                                 38.1976
부산     수영구                                                 40.221
대구     중구                                                 45.6183
부산     강서구                                                    NaN
세종     세종                                                     NaN
경기     영통구                                                    NaN
       처인구                                                    NaN
       기흥구                                                    NaN
       수지구                                                    NaN
충북     서원구                                                    NaN
       청원구                                                    NaN
       제천                                                     NaN
충남     동남구                                                    NaN
       서북구                                                    NaN
       계룡                                                     NaN
       당진                                                     NaN
       서산                                                     NaN
전남     여수                                                     NaN
경북     안동                                                     NaN
       김천                                                     NaN
경남     창원                                                     NaN
       마산합포구                                                  NaN
       마산회원구                                                  NaN
       성산구                                                    NaN
       의창구                                                    NaN
       진해구                                                    NaN
       통영                                                     NaN
제주도    제주도                                                    NaN
rank            경기     용인         1.0
       남양주        2.0
  ...
dtype: object

In [65]:
# [예제 3.6] 매매가, 전세가 지수 증감률을 계산해서 데이터프레임 형태로 저장(ch03/ 3.1 부동산 수요.ipynb)
pd.set_option('display.max_rows', 1000)
index_date = datetime(2019, 1, 1)
time_range = 12 * 15
prev_date = index_date - relativedelta(months=time_range)

print(index_date)
print(prev_date)

demand_df = pd.DataFrame()
demand_df['매매증감률'] = (price_index.loc[index_date] - price_index.loc[prev_date])/ price_index.loc[prev_date]
demand_df['전세증감률'] = (jeonse_index.loc[index_date] - jeonse_index.loc[prev_date])/jeonse_index.loc[prev_date]
# demand_df['매매증감률']
demand_df = demand_df * 100
demand_df['매매버블'] = demand_df['매매증감률'] - demand_df['매매증감률'][('전국','전국')]
demand_df['전세버블'] = demand_df['전세증감률'] - demand_df['전세증감률'][('전국','전국')]
demand_df['버블'] = demand_df['매매버블'] -  demand_df['전세버블']
sorted_df = demand_df.sort_values(by='버블')
sorted_df['rank'] = demand_df.rank()
sorted_df
# demand_df['전세증감률']
# price_ratio = demand_df['매매증감률'] - demand_df['매매증감률'][('전국','전국')]
# jeonse_ratio = demand_df['전세증감률'] - demand_df['전세증감률'][('전국','전국')]
# bubble = price_ratio - jeonse_ratio
# pd.set_option('display.max_rows', 1000)
# bubble = bubble * 100
# bubble = bubble.sort_values()
# bubble['rank'] = bubble.rank()
# bubble

# demand_df['매매증감률'] - demand_df['전세증감률']

2019-01-01 00:00:00
2004-01-01 00:00:00

TypeError: rank() got an unexpected keyword argument 'by'

In [ ]:
# [예제 3.7] 기준 날짜로부터 지난 3년간의 데이터 가져오기

prev_date2 = index_date - relativedelta(months=time_range*3)
price_index[prev_date2:index_date][:-1]

In [ ]:
# [예제 3.8] demand_df에 지난 최댓값과 기준 날짜 값의 최댓값 대비 증감률 저장

demand_df['이전최대값'] = price_index[prev_date2:index_date][:-1].max()
demand_df['최댓값대비증감률'] = (price_index.loc[index_date] - demand_df['이전최대값']) /demand_df['이전최대값']

In [ ]:
# [예제 3.9] 매매가 지수와 전세가 지수의 상승여부를 계산해 demand_df에 저장

demand_df['매매가상승'] = demand_df['매매증감률'] > 0.01
demand_df['전세가상승'] = demand_df['전세증감률'] > 0.01

In [ ]:
# [예제 3.10] 전세가 지수 상승이 매매가 지수 상승보다 빠른지와 
# 기준 날짜의 매매가 지수 값이 지난 3년의 최댓값보다 큰지 계산하여 demand_df에 저장

demand_df['더빠른전세상승'] = demand_df['전세증감률'] > demand_df['매매증감률']
demand_df['최댓값대비상승'] = demand_df['최댓값대비증감률'] > 0

In [ ]:
# [예제 3.11] 지역별로 수요 조건의 총합 구하기 (ch03/ 3.1 부동산 수요.ipynb)

demand_df['수요총합'] = demand_df[['매매가상승','전세가상승','더빠른전세상승','최댓값대비상승']].sum(axis=1)

In [ ]:
# [예제 3.12] 수요총합이 4점인 지역만 보기

demand_df = demand_df[demand_df['수요총합'] == 4]

In [ ]:
# [예제 3.13] demand_df에서 원하는 지역만 남기기 

demand_df.loc[[('서울','동대문구'), ('부산', '중구')]]

In [ ]:
# [예제 3.14] 시군 단위의 인덱스만 남기기

seleted_index = []

for name in demand_df.index:
    if name[0] is not name[1]:
        seleted_index.append((name[0], name[1]))
        
demand_df = demand_df.loc[seleted_index]

In [ ]:
# [예제 3.15] 코드를 정리해 함수화 하기 

def demand(price_index, jeonse_index, index_date, time_range):

    prev_date = index_date - relativedelta(months=time_range)
    prev_date2 = index_date - relativedelta(months=time_range*3)

    demand_df = pd.DataFrame()
    demand_df['매매증감률'] = (price_index.loc[index_date] - price_index.loc[prev_date])/ price_index.loc[prev_date].replace(0,None)
    demand_df['전세증감률'] = (jeonse_index.loc[index_date] - jeonse_index.loc[prev_date])/jeonse_index.loc[prev_date].replace(0,None)
    demand_df['이전최대값'] = price_index[prev_date2:index_date][:-1].max()
    demand_df['최댓값대비증감률'] = (price_index.loc[index_date] - demand_df['이전최대값']) /demand_df['이전최대값'].replace(0,None)

    demand_df['매매가상승'] = demand_df['매매증감률'] > 0.01
    demand_df['전세가상승'] = demand_df['전세증감률'] > 0.01
    demand_df['더빠른전세상승'] = demand_df['전세증감률'] > demand_df['매매증감률']
    demand_df['최댓값대비상승'] = demand_df['최댓값대비증감률'] > 0
    demand_df['수요총합'] = demand_df[['매매가상승','전세가상승','더빠른전세상승','최댓값대비상승']].sum(axis=1)

    demand_df = demand_df[demand_df['수요총합'] == 4]

    seleted_index = []

    for name in demand_df.index:
        if name[0] is not name[1]:
            seleted_index.append((name[0], name[1]))

    demand_df = demand_df.loc[seleted_index]
    
    return demand_df

In [ ]:
# [예제 3.16] demand 함수 사용 예시

path = r' 여러분이 내려 받은 KB 엑셀파일의 디렉터리를 넣으세요 \ KB엑셀 파일명.xls'
price_index = KBpriceindex_preprocessing(path, '매매apt')
jeonse_index = KBpriceindex_preprocessing(path, '전세apt')

index_date = datetime(2010, 1, 1)
time_range = 12

demand_ex = demand(price_index, jeonse_index, index_date, time_range)

In [ ]:
# [예제 3.17] matplotlib를 불러오고 한글폰트 

import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
from matplotlib import style
style.use('ggplot')
%matplotlib inline

font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
# 맥OS인 경우 위 두 줄을 입력하지 말고 아래 코드를 입력하세요
# rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

In [ ]:
# [예제 3.18] 특정 날짜를 기준으로 부산 중구 그래프 그리기 

si = '부산'
gu = '중구'
index_date = datetime(2010, 1, 1)

prev_date = index_date - relativedelta(months=12)
prev_date2 = index_date - relativedelta(months=36)
graph_start = index_date - relativedelta(years=3)
graph_end = index_date + relativedelta(years=3)

plt.figure(figsize=(10, 5))
plt.title(si + ' - ' + gu)
plt.plot(price_index[si][gu][graph_start:graph_end], label='매매가')
plt.plot(jeonse_index[si][gu][graph_start:graph_end], label='전세가')
plt.axvline(x=index_date, color='lightcoral', linestyle='--')
plt.axvline(x=prev_date, color='darkseagreen', linestyle='--')
plt.axvline(x=prev_date2, color='darkseagreen', linestyle='--')
plt.legend()
plt.show()

In [ ]:
# [예제 3.19] 수요전략의 결과 데이터프레임에서 지역 이름 가져오기

for name in demand_ex.index:
    print(name)

In [ ]:
# [예제 3.20] demand 함수를 이용해 선택 된 전 지역의 그래프 그리기 

index_date = datetime(2010, 1, 1)

time_range = 12
prev_date = index_date - relativedelta(months=time_range)
prev_date2 = index_date - relativedelta(months=time_range * 3)
graph_start = index_date - relativedelta(months=time_range * 3)
graph_end = index_date + relativedelta(months=time_range * 3)

num_row = int((len(demand_ex.index)-1)/2)+1

plt.figure(figsize=(15, num_row*5))
for i, spot in enumerate(demand_ex.index):
    plt.subplot(num_row, 2, i+1)
    plt.title(spot)
    si = spot[0]
    gu = spot[1]
    plt.plot(price_index[si][gu][graph_start:graph_end], label='매매가')
    plt.plot(jeonse_index[si][gu][graph_start:graph_end], label='전세가')
    plt.axvline(x=index_date, color='lightcoral', linestyle='--')
    plt.axvline(x=prev_date, color='darkseagreen', linestyle='--')
    plt.axvline(x=prev_date2, color='darkseagreen', linestyle='--')
    plt.legend(loc='lower right')
    
plt.show()